version: "3.8"

volumes:
  app-server-static:

services:
  app-server:
    build:
      context: ./flaskapp
    container_name: flaskapp
    volumes:
      - app-server-static:./flaskapp/static
    ports:
      - 5000:5000
      
  web-server:
    image: nginx
    container_name: web-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app-server-static:./flaskapp/static
    ports:
      - "8080:80"
    depends_on:
      - app-server