version: "3.8"

services:
  web-server:
    image: nginx
    container_name: web-server
    volumes:
      - ./images:/www/images/
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

  web-app:
    build:
      context: ./flaskapp
    container_name: web-page-app
    ports: 
      - 5000:5000
    depends_on:
      - web-server

