version: "3.8"

services:
  app-server:
    container_name: flaskapp
    build:
      context: ./flaskapp
    expose:
      - 5000
      
  web-server:
    image: openresty/openresty:alpine
    container_name: web-server
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/purge.lua:/usr/local/openresty/nginx/purge.lua
      - ./nginx/md5.lua:/usr/local/openresty/lualib/md5.lua
    ports:
      - 8080:80
    depends_on:
      - app-server
