version: "3.8"

services:
  app-server:
    build:
      context: ./flaskapp
    container_name: flaskapp
    expose:
      - 5000
      
  web-server:
    image: nginx
    container_name: web-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - app-server
